apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: vairome/pern-client:bd89486f0a875d235d254f0d6de6b610410ad367
          ports:
            - containerPort: 3000
