name: CI/CD react node app

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
             client:
              - 'dockerized-app/client/**'
             server:
              - 'dockerized-app/server/**'
      

  extra:
    if: build.steps.changes.outputs.client == 'true' && build.steps.changes.outputs.server == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3